### PR TITLE
No chdir - allowing relative paths in command line

### PR DESCRIPTION
**Pull request by Lockszmith-GH**
Addresses #209

### CODE REVIEW

**Comment by Lockszmith-GH** [comment]
still need to test creation to make sure does not affect pathes inside pre-hook scripts. Will update after testing

**Comment by Jip-Hop** [comment]
Looking forward to the results of testing :)

By the way the `chdir` inside `class Chroot` should be left as is. Otherwise chroot will break and the absolute symlinks inside nixos rootfs will cause trouble. E.g. when parsing `os-release`.

Maybe the solution is not to drop the chdir but instead remember the original working dir somewhere so the relative config path can still be constructed. Not sure what the best approach is.

**Comment by Lockszmith-GH** [comment]
I started by dropping everything so I can test it - but you're right, that location probably should remain.
As for chdir - in a a way that is 'bad form' to globally chdir.
if you want to preserve 'relative to a location' operation, I think a better patter would be to use the pushd/popd paradigm from bash:

pushd location of interest
perform operation accepting relative to location paths
popd location

or alternativly, calculate absolute paths all the way - which when debugging makes things easier to catch.

**Comment by Jip-Hop** [comment]
Yeah my initial design was to keep everything relative to (and included in) the `jailmaker` directory. From the perspective of `jlmkr` there'd be only this directory to care about. But with the introduction of config templates I forgot those could be located outside this directory...

**Comment by Lockszmith-GH** [comment]
In the next comment I'll document the code changes.

This comment documents descibes the automated test bash-script I used to test as many edge cases as I could think off) - Feel free to add your suggestions.

The script has 2 optional parameter invocation sets:
* `<jail type>` [`<jail name>`]
* `<template/path>` `<jail name>`

Legend:
| Arg name | Description |
|-|-|
| `<jail type>` | The template dir-name in `$SCALE_POOL_ROOT/jailmaker/templates` (it will load the `config` file within it) |
| `<jail name>`\* | The name of the jail that will be created and destroyed during the testing. <br/> If not supplied, the default is `<jail type>-test` |
| `<template/path>` | relative or absolute path to a config template. (`<jail name>` must be supplied) |

> PRE-REQUISITE:   
> \* WARNING: If `<jail name>` exists, it will be removed.

Environment variables control the test behavior:
| Variable name | Default |Description |
|-|:-:|-|
|`SCALE_POOL_ROOT`|N/A, must be exported|Env var must be defined and valid pointing to the root of the ZFS dataset hosting the `jailmaker` script dir. |
|`STOP`|0| `0` - perform all non-blocking tests<br/>`l` - only list and images, nothing else<br/>`i` - interactive test, includ console-blocking waiting for input tests (edit and shell)|
|`FULL_TEST`|0|`0` - perform a single run<br/>`1`* - perform a full-test|

> \* `FULL_TEST=1` will perform a full run ONLY when passing a `<jail type>` (will not work with `<template/path>`)

## Type of Run

In `STOP=0` (the default) all steps, except the interactive steps will be performed.
The interactive steps are steps which prompt the user for input. These are `shell` and `edit`.
In `STOP=i` all steps will be performed.

A special shorthand option exists `STOP-l` which will just run `list` and `images`, this is to test basic invocation of the script regardless of specific jails. This is also the only non-destructive mode.

## Single Run

By default, a single run in non-interactive mode will run, it runs from whatever CWD path the shell is in.

## Full Test

The Full test, starts with the single run (whether interactive or not), if successful, it continues to perform non-interactive tests with the following parameters:

| S | F | CWD | Path to template |
|:-:|:-:|-|-|
|+|+|`$SCALE_POOL_ROOT/jailmaker`|`./templates/$JAIL_TYPE/config`|
||+|`$SCALE_POOL_ROOT/jailmaker`|`templates/$JAIL_TYPE/config`|
||+|`$SCALE_POOL_ROOT/jailmaker`|`$SCALE_POOL_ROOT/jailmaker/$JAIL_CONFIG`|
||+| ~ |`$SCALE_POOL_ROOT/jailmaker/$JAIL_CONFIG`|
||+| ~ | a _temporary file_, it's contents will be copied form the `<jail type>`'s config file. |

> S - Single Run | F - Full Test

### Example invocation:
Single run, interactive mode, `nixos` jail type:

```bash
cd ${SCALE_POOL_ROOT:?must define this before running}/jailmaker \
&& sudo STOP=i SCALE_POOL_ROOT=$SCALE_POOL_ROOT $SCALE_POOL_ROOT/jailmaker/test/test-jlmkr nixos
```

Full test, default settings, `nixos` jail type:

```bash
cd ${SCALE_POOL_ROOT:?must define this before running}/jailmaker \
&& sudo FULL_TEST=1 SCALE_POOL_ROOT=$SCALE_POOL_ROOT $SCALE_POOL_ROOT/jailmaker/test/test-jlmkr nixos
```

### What to expect
A full non-interactive test run with `nixos` (which is rather lean, yet tests both pre hook and init scripts) ran for ~280 seconds.

The report summary outputs what type of run it was with CWD and path to config file and for each step, a green checkmark indicating ✅ Success, a red X symbol following the exit code❌(`<error code>`) for erros. Both follow the command executed.
In the case a step wasn't performed, a blank checkbox 🔳 followed by the name of the step will be listed.
The report is always listed in alphabetic order (although the steps are performed in an order that allows testing as much as possible while taking into account dependent steps.

**Comment by Lockszmith-GH** [comment]
* automated tests related changes I've made: added argument that can be passed to `log` and `status` so that interactive features of `joutnalctl` could be avoided.

* Removed `os.getcwd()` in `create_jail`
* Modified `remove_zfs_dataset` and `create_zfs_dataset` to work with full dataset paths. Added a safety to only allow actions within the Jailmaker dataset.
* Modified `get_zfs_dataset` to produce path for existing dataset as well as 'future' datasets, where only the parent dataset exists.
* Removed `os.chdir` from start of script.

**Comment by Lockszmith-GH** [comment]
All tests passed for nixos.
A complete full test run with `nixos` completed successfully, as well as a single interactive run.

<details><summary>Complete run output - click to expand</summary>

```console
> sudo STOP=i SCALE_POOL_ROOT=$SCALE_POOL_ROOT $SCALE_POOL_ROOT/jailmaker/test/test-jlmkr nixos
🔳 jlmkr list
NAME   RUNNING STARTUP GPU_INTEL GPU_NVIDIA OS     VERSION ADDRESSES
docker False   False   False     False      debian 12      -
🔳 jlmkr images
Downloading the image index

---
DIST             RELEASE     ARCH   VARIANT  BUILD
---
almalinux        8           amd64  default  20240627_23:08
almalinux        9           amd64  default  20240627_23:08
alt              Sisyphus    amd64  default  20240628_01:17
alt              p10         amd64  default  20240628_01:17
alt              p9          amd64  default  20240628_01:17
archlinux        current     amd64  default  20240627_04:18
centos           7           amd64  default  20240627_07:08
centos           9-Stream    amd64  default  20240627_07:08
debian           bookworm    amd64  default  20240627_05:24
debian           bullseye    amd64  default  20240627_05:24
debian           buster      amd64  default  20240627_05:24
debian           trixie      amd64  default  20240627_05:24
fedora           39          amd64  default  20240627_20:33
fedora           40          amd64  default  20240627_20:33
kali             current     amd64  default  20240627_17:14
mint             ulyana      amd64  default  20240626_08:51
mint             ulyssa      amd64  default  20240626_08:51
mint             uma         amd64  default  20240626_08:51
mint             una         amd64  default  20240626_08:51
mint             vanessa     amd64  default  20240626_08:51
mint             vera        amd64  default  20240626_08:51
mint             victoria    amd64  default  20240626_08:51
nixos            23.11       amd64  default  20240628_01:00
nixos            24.05       amd64  default  20240628_01:00
nixos            unstable    amd64  default  20240628_01:01
openeuler        20.03       amd64  default  20240627_15:48
openeuler        22.03       amd64  default  20240627_15:48
openeuler        23.09       amd64  default  20240627_15:48
opensuse         15.4        amd64  default  20240624_04:38
opensuse         15.5        amd64  default  20240624_04:20
opensuse         tumbleweed  amd64  default  20240627_05:13
oracle           7           amd64  default  20240627_07:46
oracle           8           amd64  default  20240627_07:46
oracle           9           amd64  default  20240627_07:46
rockylinux       8           amd64  default  20240627_02:06
rockylinux       9           amd64  default  20240627_02:06
slackware        15.0        amd64  default  20240627_23:08
slackware        current     amd64  default  20240627_23:17
springdalelinux  7           amd64  default  20240627_06:38
springdalelinux  8           amd64  default  20240627_06:38
springdalelinux  9           amd64  default  20240627_06:38
ubuntu           bionic      amd64  default  20240626_07:42
ubuntu           focal       amd64  default  20240626_07:42
ubuntu           jammy       amd64  default  20240626_07:42
ubuntu           lunar       amd64  default  20240626_07:42
ubuntu           mantic      amd64  default  20240626_07:42
ubuntu           noble       amd64  default  20240626_07:42
ubuntu           xenial      amd64  default  20240626_07:42
---
🔳 jlmkr create --config /mnt/tank/jailmaker/templates/nixos/config nixos-test
USE THIS SCRIPT AT YOUR OWN RISK!
IT COMES WITHOUT WARRANTY AND IS NOT SUPPORTED BY IXSYSTEMS.
Creating jail nixos-test from config template /mnt/tank/jailmaker/templates/nixos/config.

Hint: run `jlmkr.py create` without any arguments for interactive config.
Or use CLI args to override the default options.
For more info, run: `jlmkr.py create --help`

/mnt/tank/jailmaker/jails None
Using image from local cache
Unpacking the rootfs

---
You just created an Nixos 24.05 x86_64 (20240627_01:02) container.
🔳 jlmkr start nixos-test

Starting jail nixos-test with the following command:

systemd-run --property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0 --unit=jlmkr-nixos-test --working-directory=/mnt/tank/jailmaker/jails/nixos-test '--description=My nspawn jail nixos-test [created with jailmaker]' --property=ExecStartPre=/mnt/tank/jailmaker/jails/nixos-test/.ExecStartPre -- systemd-nspawn --keep-unit --quiet --boot --bind-ro=/sys/module --inaccessible=/sys/module/apparmor --machine=nixos-test --directory=rootfs --network-bridge=br1 --bind-ro=./lxd.nix:/etc/nixos/lxd.nix

Running as unit: jlmkr-nixos-test.service
🔳 jlmkr restart nixos-test
Waiting 4s seconds before test...
Wait for nixos-test to stop.
Starting jail nixos-test with the following command:

systemd-run --property=KillMode=mixed --property=Type=notify --property=RestartForceExitStatus=133 --property=SuccessExitStatus=133 --property=Delegate=yes --property=TasksMax=infinity --collect --setenv=SYSTEMD_NSPAWN_LOCK=0 --unit=jlmkr-nixos-test --working-directory=/mnt/tank/jailmaker/jails/nixos-test '--description=My nspawn jail nixos-test [created with jailmaker]' --property=ExecStartPre=/mnt/tank/jailmaker/jails/nixos-test/.ExecStartPre -- systemd-nspawn --keep-unit --quiet --boot --bind-ro=/sys/module --inaccessible=/sys/module/apparmor --machine=nixos-test --directory=rootfs --network-bridge=br1 --bind-ro=./lxd.nix:/etc/nixos/lxd.nix

Running as unit: jlmkr-nixos-test.service
🔳 jlmkr edit nixos-test
Waiting 4s seconds before test...

Restart the jail for edits to apply (if you made any).
🔳 jlmkr shell nixos-test
Waiting 4s seconds before test...
Connected to machine nixos-test. Press ^] three times within 1s to exit session.

[root@nixos:~]# echo one
one

[root@nixos:~]#
logout
Connection to machine nixos-test terminated.
🔳 jlmkr exec nixos-test /bin/sh -c echo exec successful
Waiting 4s seconds before test...
exec successful
🔳 jlmkr status nixos-test --no-pager
● jlmkr-nixos-test.service - My nspawn jail nixos-test [created with jailmaker]
     Loaded: loaded (/run/systemd/transient/jlmkr-nixos-test.service; transient)
  Transient: yes
     Active: active (running) since Thu 2024-06-27 22:31:05 EDT; 21s ago
    Process: 3445762 ExecStartPre=/mnt/tank/jailmaker/jails/nixos-test/.ExecStartPre (code=exited, status=0/SUCCESS)
   Main PID: 3445763 (systemd-nspawn)
     Status: "Container running: Ready."
      Tasks: 21
     Memory: 30.0M
        CPU: 2.537s
     CGroup: /system.slice/jlmkr-nixos-test.service
             ├─payload
             │ ├─3445765 /run/current-system/systemd/lib/systemd/systemd
             │ ├─3445864 /nix/store/d9ff8aqv537mlhpinncx6dwc7a5ky6gk-systemd-255.6/lib/systemd/systemd-journald
             │ ├─3446016 /nix/store/d9ff8aqv537mlhpinncx6dwc7a5ky6gk-systemd-255.6/lib/systemd/systemd-resolved
             │ ├─3446042 /nix/store/d9ff8aqv537mlhpinncx6dwc7a5ky6gk-systemd-255.6/lib/systemd/systemd-networkd
             │ ├─3446072 /nix/store/w44ykc1hjhg6z1m06x1h38p6zk86h91b-nsncd-unstable-2024-01-16/bin/nsncd
             │ ├─3446073 /nix/store/nn54yahdasinv9hyk1hjwpakw8sqqyq0-dbus-1.14.10/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile …
             │ ├─3446086 /nix/store/d9ff8aqv537mlhpinncx6dwc7a5ky6gk-systemd-255.6/lib/systemd/systemd-logind
             │ ├─3446089 agetty --login-program /nix/store/3kgyqixfqf6vhq3cw41vgxv2i0x2fayz-shadow-4.14.6/bin/login --noclear --keep-baud console 1…
             │ ├─3446391 /nix/store/d9ff8aqv537mlhpinncx6dwc7a5ky6gk-systemd-255.6/lib/systemd/systemd --user
             │ └─3446394 "(sd-pam)"
             └─supervisor
               └─3445763 /usr/bin/systemd-nspawn --keep-unit --quiet --boot --bind-ro=/sys/module --inaccessible=/sys/module/apparmor --machine=nix…

Jun 27 22:31:07 kateryna systemd-nspawn[3445763]: [  OK  ] Finished Wait for Network to be Configured.
Jun 27 22:31:07 kateryna systemd-nspawn[3445763]: [  OK  ] Reached target Network is Online.
Jun 27 22:31:07 kateryna systemd-nspawn[3445763]: [  OK  ] Reached target Multi-User System.
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]: <<< Welcome to NixOS 24.05.2150.89c49874fb15 (x86_64) - console >>>
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]: Log in as "root" with an empty password.
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
🔳 jlmkr log nixos-test -n 10
Jun 27 22:31:07 kateryna systemd-nspawn[3445763]: [  OK  ] Finished Wait for Network to be Configured.
Jun 27 22:31:07 kateryna systemd-nspawn[3445763]: [  OK  ] Reached target Network is Online.
Jun 27 22:31:07 kateryna systemd-nspawn[3445763]: [  OK  ] Reached target Multi-User System.
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]: <<< Welcome to NixOS 24.05.2150.89c49874fb15 (x86_64) - console >>>
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]: Log in as "root" with an empty password.
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
Jun 27 22:31:08 kateryna systemd-nspawn[3445763]:
🔳 jlmkr stop nixos-test
Wait for nixos-test to stop.🔳 jlmkr remove nixos-test <<<nixos-test

CAUTION: Type "nixos-test" to confirm jail deletion!



Cleaning up: /mnt/tank/jailmaker/jails/nixos-test.


Report for:
        CWD: /mnt/tank/jailmaker/templates/docker            JAIL_CONFIG: /mnt/tank/jailmaker/templates/nixos/config

✅ jlmkr create --config /mnt/tank/jailmaker/templates/nixos/config nixos-test
✅ jlmkr edit nixos-test
✅ jlmkr exec nixos-test /bin/sh -c 'echo exec successful'
✅ jlmkr images
✅ jlmkr list
✅ jlmkr log nixos-test -n 10
✅ jlmkr remove nixos-test <<<'nixos-test'
✅ jlmkr restart nixos-test
✅ jlmkr shell nixos-test
✅ jlmkr start nixos-test
✅ jlmkr status nixos-test --no-pager
✅ jlmkr stop nixos-test
Stopped: Single Test
[ble: elapsed 60.793s (CPU 58.6%)]
```

</details>

##### Report Summary

**Comment by Jip-Hop** [comment]
Thanks again for all this effort @Lockszmith-GH! For me it's easier to review and accept changes when they're offered in smaller bits. For example this PR was about fixing `chdir` bug, but in order to fix it I now also need to accept the test script and other changes (for which I'm not immediately sure if they're required for the `chdir` fix or required for the test script, or perhaps they are not required by either and actually independent improvements).

For example I'd easily accept passing args to log and status if that was in it's own PR. I've cherry picked that commit into the develop branch for now.

You think you could split these changes into individual PRs? [Automated testing](https://github.com/Jip-Hop/jailmaker/issues/86) would be a great addition but I'd like to discuss it a bit more (and understand the approach better) and I don't think fixing the `chdir` bug should depend on it.

P.S. if you check "Allow edits by maintainer" in the PR I can also make changes to your branch. E.g. I tried fixing some spelling and shellcheck warnings inside `test/test-jlmkr` but couldn't push my changes.

**Comment by Lockszmith-GH** [comment]
Because I chose to organize repos using Organizations, [I don't have](https://github.com/orgs/community/discussions/5634) the "Allow edits by maintainer" checkbox. Sorry about that.

I'll split the commit into a separate PR. I'll also pass the shell script through shellcheck and a spellchecker (I did all the work on my TrueNAS SCALE machine, where I didn't install all of the plugins)

Switching to draft until all of that is done.

**Comment by Jip-Hop** [comment]
@Lockszmith-GH please see #86 regarding automated testing.

**Comment by Lockszmith-GH** [comment]
I will, this weekend I'm away, will continue throughout the week.

**Comment by Lockszmith-GH** [comment]
Removed the automated testing code from this branch.

**Comment by Jip-Hop** [comment]
> I did however invite you to join the repo.

Thanks but I don't want to join a GitHub organization for this purpose.

> When you accept an invitation to join an organization, the organization owners may be able to see:
> 
> Your public profile information
> Your email address
> If you have two-factor authorization enabled
> Repositories you have access to within the organization, and your access level
> Certain activity within the organization
> Country of request origin
> Your IP address

https://docs.github.com/en/enterprise-cloud@latest/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/about-organization-membership

**Comment by Lockszmith-GH** [comment]
sorry about that, I'm currently stuck with the organization - just because of past choices.

**Comment by Lockszmith-GH** [comment]
I see the IP - probably in logs - all good. I'll check the branch

**Comment by Lockszmith-GH** [comment]
The develop branch looks good to me.

**Comment by Lockszmith-GH** [comment]
The develop branch looks good to me. Closing this PR.

**Pull request closed without merging**
