### PR TITLE
Fix ZFS mount spacing from /proc/mounts for datasets with spaces

### PR DESCRIPTION
**Pull request by templehasfallen**
Fix for #122

### CODE REVIEW

**Comment by Jip-Hop** [comment]
I think there are even more edge cases: https://stackoverflow.com/a/13576641

**Comment by templehasfallen** [comment]
Should be fixed now for spaces

**Comment by Jip-Hop** [comment]
Thanks for picking this up so quickly :)

But this needs to cover some more edge cases. What if the dataset nane already contains a backslash, or even a tab or newline? Are there more cases?

**Comment by templehasfallen** [comment]
Regardless, I've added newline, tab, backslash and tested it.

**Comment by templehasfallen** [comment]
> Thanks again for you effort :)
> 
> Can you explain how you tested it?
> 

I tested the spaces directly on the systems and I added the tab, newline, backslash I just tested that the code block is doing what its supposed to. Those extra 3 lines aren't rocket science :D

> Seems like the alias in bashrc and zshrc is broken due to the spaces. After correcting it to: `alias jlmkr='/mnt/pool\ with\ spaces/nobackslash/jailmaker/jlmkr.py'` and sourcing again with `. /root/.zshrc` the `jlmkr` command now works again and it does successfully create a dataset for my test jail, and cleans it up when removing the jail.
>
> So in conclusion, I think we only have to be concerned with the spaces, as you initially suggested. The alias needs to be fixed too to support this (but I suppose this was already broken before we introduces dataset support). What do you think?

Yeah, I hadn't thought of the alias as I was always testing it directly. But that should be an easy fix. Personally I just have an alias for `j` which I manually create.

> The reason I zoom in on this is because jailmaker now has the capability to recursively destroy datasets... So we should be very careful!

I absolutely agree :)

**Comment by Jip-Hop** [comment]
```
            fields3 = [line.replace("\\040"," ") for line in unclean_fields]
            fields2 = [line.replace("\\011"," ") for line in fields3]
            fields1 = [line.replace("\\012"," ") for line in fields2]
            fields = [line.replace("\\134"," ") for line in fields1]
```

You replaced the 4 different characters with a space, instead of the corresponding character it was supposed to encode. I've fixed the space issue in the develop branch.

Thanks though!

**Pull request closed without merging**
