### PR TITLE
Follow Debian guidelines for launching editors

### PR DESCRIPTION
**Pull request by maxnordlund**
This is how most other tools work when they want the user to edit a file.

### CODE REVIEW

**Comment by Lockszmith-GH** [comment]
Thanks for implementing this, tested and works.

**Comment by maxnordlund** [comment]
I missed that issue, and VISUAL. So I've included that as well (and squashed the commits while I was at it).

**Comment by Lockszmith-GH** [comment]
thanks @maxnordlund, obviously, still works - just tested it.

Just a reminder that `/usr/bin/editor` in debian by default points to `nano`, so `editor` instead of `nano` makes the solution completly in compliance of [debain's guidelines](https://www.debian.org/doc/debian-policy/ch-customized-programs.html#editors-and-pagers). (allowing for system-wide defaults to be changed with `update-alternatives`)

**Comment by Jip-Hop** [comment]
If we want to be really complete then we need to check if the command exists too. I think a `get_text_editor` method would make sense instead of the current global variable. It could loop over VISUAL and EDITOR and check each time if it is a command using `shutil.which` and return this string if it is a valid command. If neither VISUAL and EDITOR have returned then return `/usr/bin/editor`.

This has the added benefit of making this bit redundant:
https://github.com/Jip-Hop/jailmaker/blob/48675557b85e7ab00ffaaf6625eb7889309bc619/jlmkr.py#L1509-L1514

**Comment by maxnordlund** [comment]
OK, so I took the time to do this properly. It now closely follows the Debian guidelines, including both looking up `editor` before falling back to `/usr/bin/editor`, and if all else fails falls back to the old hardcoded `nano`.

**Pull request merged**
