### PR TITLE
Add nvidia jailmaker config

### PR DESCRIPTION
**Pull request by dasunsrule32**
This config will:

 * Install all repos needed
 * Install all dependancies
 * Install docker
 * Install nvidia-container-toolkit
 * Reconfigure docker dameon to en-
   able the nvidia runtime

### CODE REVIEW

**Comment by neoKushan** [comment]
Rather than adding a whole separate config for nvidia, is there no way we can leverage the existing `gpu_passthrough_nvidia` flag to perform the nvidia specific installation and configuration? 

Would require changes to the main jlmkr code, which I appreciate might not be ideal.

**Comment by dasunsrule32** [comment]
Maybe wrap the nvidia specific configs with if logic based on the value of `gpu_passthrough_nvidia`?

**Comment by neoKushan** [comment]
Yeah exactly, then there's only one template to maintain going forward rather than two

**Comment by Lockszmith-GH** [comment]
I always feel a bit queasy of placing too much logic in the `initial_setup` step, makes debugging rather hard, especially when getting into new-line, quoting and other possible issues.
Would placing a script in the `rootfs/` not be a better design?

**Comment by Jip-Hop** [comment]
Ideally we would not have a `initial_setup` at all. But that means setting up infrastructure to regularly build rootfs images from various distros with some packages installed and configured.

What are the quoting and line break issues you mention? The only requirement is that the script lines are indented...

Scripts can't be placed in the rootfs because then the config file would no longer be 'complete' on its own. The point of the config file is to be able to setup in a reproducible way without depending on external files.

**Comment by Lockszmith-GH** [comment]
Maybe just my bad luck, and indeed in my previous attempt there was a blank line without indentation. If the only limitation is indentation, I would agree, initial_setup might be the way to go.

**Comment by Jip-Hop** [comment]
Hi @dasunsrule32 please try the pre-release of jailmaker version v1.4.0 from the [develop branch](https://github.com/Jip-Hop/jailmaker/tree/develop) together with [the updated docker config template](https://github.com/Jip-Hop/jailmaker/blob/develop/templates/docker/config). It now includes conditional install of `nvidia-container-toolkit` depending on the value of `gpu_passthrough_nvidia`. This means there's only 1 docker config template to maintain as @neoKushan suggested.

Please let me know if it works as intended so we can close this pull request.

**Comment by dasunsrule32** [comment]
> Hi @dasunsrule32 please try the pre-release of jailmaker version v1.4.0 from the [develop branch](https://github.com/Jip-Hop/jailmaker/tree/develop) together with [the updated docker config template](https://github.com/Jip-Hop/jailmaker/blob/develop/templates/docker/config). It now includes conditional install of `nvidia-container-toolkit` depending on the value of `gpu_passthrough_nvidia`. This means there's only 1 docker config template to maintain as @neoKushan suggested.
> 
> Please let me know if it works as intended so we can close this pull request.

Looks good! I built a machine from your config and only added the bind mounts needed for access to my data and enabled `gpu_passthrough_nvidia`. Launched Plex and watch live TV. It was using hardware transcoding. Didn't need to bind the `/usr` mount either for the nvidia libs.

**Comment by dasunsrule32** [comment]
Closing, as @Jip-Hop added to the origin/develop branch needed changes for nvidia to work out of the box now.

**Comment by Jip-Hop** [comment]
Nice!

> Didn't need to bind the /usr mount either for the nvidia libs.

Which version of SCALE did you try this on? You're saying you don't experience https://github.com/Jip-Hop/jailmaker/issues/127?

**Comment by dasunsrule32** [comment]
> Nice!
> 
> > Didn't need to bind the /usr mount either for the nvidia libs.
> 
> Which version of SCALE did you try this on? You're saying you don't experience https://github.com/Jip-Hop/jailmaker/issues/127?

It's working fine on Dragonfish 24.04 with the updated config.

**Pull request closed without merging**
